### ISSUE TITLE
Effective canister id in URL orcis-3qaaa-aaaad-qaaaa-cai does not match requested canister id: zsumk-yqaaa-aaaad-p34ya-cai.)

### ISSUE THREAD

**Issue by lastmjs** [mraszyk/sexp#1]
Saving me a lot of work! Unfortunately I haven't gotten the script to progress beyond just getting the canister ranges for each subnet.

I keep getting these types of errors:

```
HttpError(Http Error: status 400 Bad Request, content type "application/cbor", content: Effective canister id in URL orcis-3qaaa-aaaad-qaaaa-cai does not match requested canister id: zsumk-yqaaa-aaaad-p34ya-cai.)
```

**Comment by lastmjs** [comment]
I wonder if this effective canister id requirement changed recently? I can't even get the unmodified script to return the canister controllers and module hashes because of these errors.

**Comment by lastmjs** [comment]
I'm not sure how this batching is supposed to work if the effective canister id has to match the canister id in each path...

**Comment by mraszyk** [comment]
Unfortunately this tool does not work anymore because of the condition that effective canister id in the URL has to match all canister ids in every path. This condition has been in the specification for a long time, but it was not enforced by the implementation. Recently the condition started to be enforced by the nodes and this made my tool stop working.

**Comment by lastmjs** [comment]
Ah...too bad, I was afraid of that

**Comment by let4be** [comment]
So how do you check for canister metadata now?

I tried requesting the path /canister/<canister_id>/module_hash and got the same error...
I'm trying to iterate through all canisters to collect some data, cannot find any working example
